import { useMemo } from 'react'
import { barcodeSvg, type BarcodeStyle } from '../lib/barcode'

/** Renders a barcode. The markup is generated by JsBarcode from the value; nothing user-typed is injected as HTML. */
export function BarcodeSvg({ value, style, className }: { value: string; style: BarcodeStyle; className?: string }) {
  const result = useMemo(() => barcodeSvg(value, style), [value, style])
  if (!result.ok) return <p role="alert" className="text-center text-sm text-ink-muted">{result.error}</p>
  return <div className={className} dangerouslySetInnerHTML={{ __html: result.svg }} />
}
