"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 19:28:01.208685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('receipt_header_text', sa.Text(), nullable=True),
    sa.Column('receipt_footer_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('flavor', sa.String(length=50), nullable=True),
    sa.Column('nicotine_type', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('nicotine_strength', sa.String(length=20), nullable=True),
    sa.Column('coil_resistance_ohm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('device_variant', sa.String(length=80), nullable=True),
    sa.Column('buying_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('buying_price >= 0 AND selling_price >= 0', name='ck_products_prices'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_flavor'), 'products', ['flavor'], unique=False)
    op.create_table('branch_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_threshold', sa.Integer(), server_default='5', nullable=False),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_inventory_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'branch_id', name='uq_inventory_product_branch')
    )
    op.create_index(op.f('ix_branch_inventory_branch_id'), 'branch_inventory', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_inventory_product_id'), 'branch_inventory', ['product_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','manager','cashier')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), server_default='cash', nullable=False),
    sa.Column('amount_tendered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('change_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash','card')", name='ck_sales_payment'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index('ix_sales_branch_created', 'sales', ['branch_id', 'created_at'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_branch_id'), 'stock_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_branch_id', sa.Integer(), nullable=False),
    sa.Column('to_branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','in_transit','received','cancelled')", name='ck_transfer_status'),
    sa.CheckConstraint('from_branch_id <> to_branch_id', name='ck_transfer_different_branches'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['to_branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_from_branch_id'), 'stock_transfers', ['from_branch_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_status'), 'stock_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_branch_id'), 'stock_transfers', ['to_branch_id'], unique=False)
    op.create_table('z_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('receipts_count', sa.Integer(), nullable=False),
    sa.Column('items_sold', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('card_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_variance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'business_date', name='uq_zreport_branch_date')
    )
    op.create_index(op.f('ix_z_reports_branch_id'), 'z_reports', ['branch_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sale_item_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_table('stock_transfer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_events_transfer_id'), 'stock_transfer_events', ['transfer_id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_transfer_item_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'product_id', name='uq_transfer_item_product')
    )
    op.create_index(op.f('ix_stock_transfer_items_transfer_id'), 'stock_transfer_items', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transfer_items_transfer_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_events_transfer_id'), table_name='stock_transfer_events')
    op.drop_table('stock_transfer_events')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_z_reports_branch_id'), table_name='z_reports')
    op.drop_table('z_reports')
    op.drop_index(op.f('ix_stock_transfers_to_branch_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_status'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_branch_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_branch_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_sales_branch_created', table_name='sales')
    op.drop_table('sales')
    op.drop_table('users')
    op.drop_index(op.f('ix_branch_inventory_product_id'), table_name='branch_inventory')
    op.drop_index(op.f('ix_branch_inventory_branch_id'), table_name='branch_inventory')
    op.drop_table('branch_inventory')
    op.drop_index(op.f('ix_products_flavor'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('branches')
    # ### end Alembic commands ###
